---

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

# Metrics
Metrics/BlockLength:
  Exclude:
    - example/**/*
    - spec/**/*
    - rspec-junit-formatter-bitbucket.gemspec

Metrics/LineLength:
  Exclude:
    - example/**/*
    - spec/**/*

# RSpec
RSpec/DescribeClass:
  Exclude:
    - example/**/*
