language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /home/travis/.rvm
    - /usr/local/bundle

rvm:
  - 2.6
  - 2.5
  - 2.4

gemfile:
  - gemfiles/rspec_3_1.gemfile
  - gemfiles/rspec_3_2.gemfile
  - gemfiles/rspec_3_3.gemfile
  - gemfiles/rspec_3_4.gemfile
  - gemfiles/rspec_3_5.gemfile
  - gemfiles/rspec_3_6.gemfile
  - gemfiles/rspec_3_7.gemfile
  - gemfiles/rspec_3_8.gemfile

before_install:
  - gem install bundler -v 1.17.3

script:
  - bundle exec rspec -f d
  - if [ "$TRAVIS_BRANCH" == "master" ]; then bundle exec rubocop -D; fi

before_deploy:
  - gem install dpl

deploy:
  provider: rubygems
  api_key:
    secure: OWuVCekC/FzcZtxbvItOiJmbje9Xo29TdBcb8+HXVtxSJYTpRYlX+/QS6VbvznOX8WHkQ+0n8EkKJlzFnqBncat2JXyOa/VS+S1cL4E7OT1cieNXMPWpCB+5O49nS+OSX90ls5nyFl6iCLLVmzunLUCElfHjySWxHXtu/91kVE7YGCDuU+nsnRdU4N9rMBNzn04r1ygKcl7WjuZ7uytt4bX+fbdAPfP1EFa1iuRWzqnqZqleNDsdYMLWVsKtBRY+eXw65u2+xGVTBs9HGC5cHZ65zjV+XiL4fJIfxXqA4qdCaEH/CkQVVdF8IUyJu5xEi6GkCQaEgC7LaNY90ca2Qh3WBnsC0QD2xgYQLxs/gnAyBOXtlZis6RnQdHeCN60lUdSX0M4lTX+7M++Iva6VVepZ2NxIWUvEbD/FGO9XuWX2TSncTk3tfmf+i173CS5XT6ahW6QJ4Bt/VDc2NAV/Y7SI3JOuthWt1rwornN8Qm3BqrrZ+xibSwMKxxnitbSREUvQG/YBCRuWuBJK+XahZc/lcXWrTXVRzGk9gOZHRJjaMamXvv9g860ansxLCXQ5OOW/HFt4PBxNhRUOuMNaVTTp8plbRsmfUtxPPntrfXUnB/P/pD7FyfkJPfQaizZCUrS4ecA7YNqtsBIOsQGrkYqakf4tWe5JxMKOsBB7d9Y=
  gem: rspec_junit_formatter_bitbucket
  on:
    repo: dazzl-tv/ruby-rabbitmq-janus
    condition: $TRAVIS_BRANCH =~ ^develop|master$
  skip_cleanup: true

notifications:
  email: false
  slack:
    on_success: always
    rooms:
      secure: wq9V5QaS9tQPr0gaHtRCuLPbMei+gO6tHNwkDFbNUo9SFb1W/0zdxapnxQhxIcyqYfLanvnjprQHme3OXJnVP59jbG4CIfe0NMcOO4s+DYBJvEBEj2+li263A96mJCdXxVojDEZ83E/0+PppfNut+CBtvWikAkMyvvbPNyd0XkQ7dYK6iWEdLBRjDmC8HYRPZgLAcHADB85F60/BuUwsWkZhCyymAXU1McPVFu8OMBpb7LJhLy9MqB5W6VpOlmUYDeTasl5h+tV7ci2cr8Mcu6EAuSUWMG/bBm57z65cEG7kz750gw1Vt8h+mUgcmWfsXBbsJZrh7xpHOulynMcf0rwVcqanvfb9suHYHf0HXon9+ljlwbP2J91wrQqezmvZqhpekPYXD3Qz8qCtdSzhSOdVzE6LaAtDKrj6p9CJ1hwhp5tWUA1roz8pNdKCOHNkmcrWCOggnhDlxrBkwwVoDvVfIl9yL1kezL87mD8vRrSJWRzKjoE85fjFJM9JR6Ie/Bcf4FjWeWRNwAv4LrLOUBDI8Bs0KNdsw+pK/69EEG5N5gnqGmqs6KOY7Ucs75Hq3ZWop85GFocQnw0k4U6YarDvzrTKz/hcrSTCwnNG8jkpKRQ6x+76rlLPcXwaGkL34AmVJ7SFu8a5u8UJUYigPej6c58rBg5wwcvw++izUKg=
