language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /home/travis/.rvm
    - /usr/local/bundle

rvm:
  #- 2.6
  #- 2.5
  - 2.4

gemfile:
  - gemfiles/rspec_3_1.gemfile
  - gemfiles/rspec_3_2.gemfile
  - gemfiles/rspec_3_3.gemfile
  - gemfiles/rspec_3_4.gemfile
  - gemfiles/rspec_3_5.gemfile
  - gemfiles/rspec_3_6.gemfile
  - gemfiles/rspec_3_7.gemfile
  - gemfiles/rspec_3_8.gemfile

script:
  - bundle update --bundler
  - gem install bundler -v 1.17.3
  - bundle exec rspec -f d
  - if [ "$TRAVIS_BRANCH" == "master" ]; then bundle exec rubocop -D; fi
